const serviciosMock = [
    {
      id: "1",
      tipoAuto: "Sedán",
      colorAuto: "Rojo",
      marca: "Toyota",
      costoServicio: 200,
      tipoServicio: "Lavado exterior",
      placas: "ABC123",
      fecha: "2024-11-25",
    },
    {
      id: "2",
      tipoAuto: "SUV",
      colorAuto: "Negro",
      marca: "Honda",
      costoServicio: 350,
      tipoServicio: "Limpieza interior",
      placas: "XYZ789",
      fecha: "2024-11-25",
    },
    {
      id: "3",
      tipoAuto: "Camioneta",
      colorAuto: "Blanco",
      marca: "Ford",
      costoServicio: 450,
      tipoServicio: "Encerado",
      placas: "JKL456",
      fecha: "2024-11-24",
    },
    {
      id: "4",
      tipoAuto: "Sedán",
      colorAuto: "Azul",
      marca: "Chevrolet",
      costoServicio: 300,
      tipoServicio: "Pulido",
      placas: "MNO678",
      fecha: "2024-11-24",
    },
    {
      id: "5",
      tipoAuto: "Hatchback",
      colorAuto: "Gris",
      marca: "Volkswagen",
      costoServicio: 250,
      tipoServicio: "Lavado completo",
      placas: "PQR234",
      fecha: "2024-11-23",
    },
  ];
  
  export default serviciosMock;
  