const serviciosMock = [
  {
    id: "1",
    tipoAuto: "Sedán",
    colorAuto: "Red",
    marca: "Toyota",
    costoServicio: 200,
    tipoServicio: "Lavado exterior",
    placas: "ABC123",
    fecha: "2024-11-25",
    imagen: "carroMediano",
  },
  {
    id: "2",
    tipoAuto: "SUV",
    colorAuto: "Black",
    marca: "Honda",
    costoServicio: 350,
    tipoServicio: "Limpieza interior",
    placas: "XYZ789",
    fecha: "2024-11-25",
    imagen: "carroGrande",
  },
  {
    id: "3",
    tipoAuto: "Camioneta",
    colorAuto: "White",
    marca: "Ford",
    costoServicio: 450,
    tipoServicio: "Encerado",
    placas: "JKL456",
    fecha: "2024-11-24",
    imagen: "carroGrande",
  },
  {
    id: "4",
    tipoAuto: "Sedán",
    colorAuto: "Blue",
    marca: "Chevrolet",
    costoServicio: 300,
    tipoServicio: "Pulido",
    placas: "MNO678",
    fecha: "2024-11-24",
    imagen: "carroMediano",
  },
  {
    id: "5",
    tipoAuto: "Hatchback",
    colorAuto: "Gray",
    marca: "Volkswagen",
    costoServicio: 250,
    tipoServicio: "Lavado completo",
    placas: "PQR234",
    fecha: "2024-11-23",
    imagen: "carroChico",
  },
];

export default serviciosMock;
